"""profile_sect_type

Revision ID: 5896203132e7
Revises: 6f0e8fff647c
Create Date: 2023-02-20 11:22:19.207387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5896203132e7'
down_revision = '6f0e8fff647c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE profilesectiontype ADD VALUE 'CHILDREN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE profilesectiontype RENAME TO profilesectiontype_old")
    op.execute("CREATE TYPE profilesectiontype AS ENUM('PERSONAL', 'EDUCATION', 'SCORE', 'GRADE', 'AWARD', 'COLLEGE', 'LEADERSHIP', 'VOLUNTARY_WORK', 'INTERNSHIP', 'ACTIVITY')")
    op.execute((
        "ALTER TABLE profileprivacy ALTER COLUMN profile_section_type TYPE profilesectiontype USING "
        "profilesectiontype::text::profilesectiontype"
    ))
    op.execute("DROP TYPE profilesectiontype_old")
    # ### end Alembic commands ###
