"""added ids in user profile table for search feature

Revision ID: 5986e6084992
Revises: 841ffc88f737
Create Date: 2023-10-18 09:01:23.404744

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5986e6084992'
down_revision = '841ffc88f737'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('disability_id', sa.UUID(), nullable=True))
    op.add_column('userprofile', sa.Column('family_type_id', sa.UUID(), nullable=True))
    op.add_column('userprofile', sa.Column('socio_economic_group_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'socio_economic_group_id')
    op.drop_column('userprofile', 'family_type_id')
    op.drop_column('userprofile', 'disability_id')
    # ### end Alembic commands ###
