"""added user karma table to sync karma post service

Revision ID: 841ffc88f737
Revises: ecd4931c2a02
Create Date: 2023-10-17 11:35:14.385704

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '841ffc88f737'
down_revision = 'ecd4931c2a02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userkarma',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tag_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(length=1024), nullable=True),
        sa.Column('karma_posts', sa.Integer(), nullable=True),
        sa.Column('karma_duration', sa.Integer(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userkarma')
    # ### end Alembic commands ###
