"""add_profile_city

Revision ID: cb5e67c9d120
Revises: 5896203132e7
Create Date: 2023-02-24 09:26:09.227666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5e67c9d120'
down_revision = '5896203132e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'city')
    # ### end Alembic commands ###
