"""added cascade on delete on some remaining table

Revision ID: e7bab4310660
Revises: 3f7ea0142716
Create Date: 2023-10-30 10:15:57.654505

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e7bab4310660'
down_revision = '3f7ea0142716'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collegeuniversities_profile_id_fkey', 'collegeuniversities', type_='foreignkey')
    op.create_foreign_key(None, 'collegeuniversities', 'userprofile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('education_address_id_fkey', 'education', type_='foreignkey')
    op.create_foreign_key(None, 'education', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'education', type_='foreignkey')
    op.create_foreign_key('education_address_id_fkey', 'education', 'address', ['address_id'], ['id'])
    op.drop_constraint(None, 'collegeuniversities', type_='foreignkey')
    op.create_foreign_key('collegeuniversities_profile_id_fkey', 'collegeuniversities', 'userprofile', ['profile_id'], ['id'])
    # ### end Alembic commands ###
