"""alter_userprofile_schema

Revision ID: ecd4931c2a02
Revises: 3d2884972404
Create Date: 2023-07-19 12:13:34.678824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd4931c2a02'
down_revision = '3d2884972404'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('disability', sa.String(length=255), nullable=True))
    op.add_column('userprofile', sa.Column('family_type', sa.String(length=255), nullable=True))
    op.add_column('userprofile', sa.Column('socio_economic_group', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('UserProfile__ts_vector__', table_name='userprofile', postgresql_using='gin')
    op.drop_column('userprofile', 'socio_economic_group')
    op.drop_column('userprofile', 'family_type')
    op.drop_column('userprofile', 'disability')
    # ### end Alembic commands ###
